version: "3.7"

services:
    web:
        image: cynax/php:7.4-fpm
        volumes:
            - .:/var/www/html
        ports:
            - 80:8000
        command: bash -c 'php artisan serve --host=0.0.0.0'
        depends_on:
            - db
        links:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PORT: 3306
        entrypoint:
            sh -c "echo 'CREATE DATABASE IF NOT EXISTS learn_que; CREATE DATABASE IF NOT EXISTS quadmin;' > /docker-entrypoint-initdb.d/init.sql; /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
            # makes learn_que and quadmin database
        ports:
            - 8912:3306
